//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO_SACH_TRA_TRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAO_CAO_SACH_TRA_TRE()
        {
            this.CT_BAO_CAO_SACH_TRA_TRE = new HashSet<CT_BAO_CAO_SACH_TRA_TRE>();
        }
    
        public int IDBaoCaoSachTraTre { get; set; }
        public System.DateTime NgayBaoCao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAO_CAO_SACH_TRA_TRE> CT_BAO_CAO_SACH_TRA_TRE { get; set; }
    }
}
