//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO_SACH_MUON_THEO_THE_LOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAO_CAO_SACH_MUON_THEO_THE_LOAI()
        {
            this.CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI = new HashSet<CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI>();
        }
    
        public int IDBaoCaoSachMuonTheoTheLoai { get; set; }
        public int ThangBaoCao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI> CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI { get; set; }
    }
}
