//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI
    {
        public int ID_CT_BaoCaoSachMuonTheoTheLoai { get; set; }
        public int IDTheLoai { get; set; }
        public int IDBaoCaoSachMuonTheoTheLoai { get; set; }
        public int SoLuotMuon { get; set; }
        public double TiLe { get; set; }
    
        public virtual BAO_CAO_SACH_MUON_THEO_THE_LOAI BAO_CAO_SACH_MUON_THEO_THE_LOAI { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
