//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAO_CAO_SACH_TRA_TRE
    {
        public int ID_CT_BaoCaoSachTraTre { get; set; }
        public int IDSach { get; set; }
        public int IDBaoCaoSachTraTre { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public int SoNgayTraTre { get; set; }
    
        public virtual BAO_CAO_SACH_TRA_TRE BAO_CAO_SACH_TRA_TRE { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
