//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUTRA
    {
        public int ID_CT_PhieuTra { get; set; }
        public int IDPhieuTra { get; set; }
        public int IDPhieuMuon { get; set; }
        public int SoNgayMuon { get; set; }
        public Nullable<double> TienPhat { get; set; }
        public int IDSach { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual PHIEUTRA PHIEUTRA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
