//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIENPHAT
    {
        public int IDPHIEUTHUTIENPHAT { get; set; }
        public int IDDocGia { get; set; }
        public double SoTienThu { get; set; }
        public Nullable<double> TongNo { get; set; }
        public Nullable<double> ConLai { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
