//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CT_BAO_CAO_SACH_TRA_TRE = new HashSet<CT_BAO_CAO_SACH_TRA_TRE>();
            this.CT_PHIEUMUON = new HashSet<CT_PHIEUMUON>();
            this.CT_PHIEUTRA = new HashSet<CT_PHIEUTRA>();
        }
    
        public int IDSach { get; set; }
        public string TenSach { get; set; }
        public int IDTheLoai { get; set; }
        public int IDTacGia { get; set; }
        public int NamXuatBan { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public double TriGia { get; set; }
        public bool TinhTrang { get; set; }
        public string NhaXuatBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAO_CAO_SACH_TRA_TRE> CT_BAO_CAO_SACH_TRA_TRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUMUON> CT_PHIEUMUON { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
    }
}
