//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int TuoiToiThieu { get; set; }
        public int TuoiToiDa { get; set; }
        public int ThoiHanGiaTriThe { get; set; }
        public int KhoangCachNamXuatBanToiDa { get; set; }
        public int SoLuongSachMuonToiDa { get; set; }
        public int SoNgayMuonToiDa { get; set; }
        public double TienPhat { get; set; }
    }
}
