//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THUVIENEntities : DbContext
    {
        public THUVIENEntities()
            : base("name=THUVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAO_CAO_SACH_MUON_THEO_THE_LOAI> BAO_CAO_SACH_MUON_THEO_THE_LOAI { get; set; }
        public virtual DbSet<BAO_CAO_SACH_TRA_TRE> BAO_CAO_SACH_TRA_TRE { get; set; }
        public virtual DbSet<CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI> CT_BAO_CAO_SACH_MUON_THEO_THE_LOAI { get; set; }
        public virtual DbSet<CT_BAO_CAO_SACH_TRA_TRE> CT_BAO_CAO_SACH_TRA_TRE { get; set; }
        public virtual DbSet<CT_PHIEUMUON> CT_PHIEUMUON { get; set; }
        public virtual DbSet<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual DbSet<DOCGIA> DOCGIAs { get; set; }
        public virtual DbSet<LOAIDOCGIA> LOAIDOCGIAs { get; set; }
        public virtual DbSet<PHIEUMUON> PHIEUMUONs { get; set; }
        public virtual DbSet<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHATs { get; set; }
        public virtual DbSet<PHIEUTRA> PHIEUTRAs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TACGIA> TACGIAs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
    }
}
